# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

use_frameworks!

target 'Blogz4Dayz' do

pod 'SQLiteModel'
pod 'Neon'
pod 'NYTPhotoViewer', '~> 1.1.0'

end

target 'Blogz4DayzTests' do

pod 'SQLiteModel'

end

